# Uncomment the lines below you want to change by removing the # in the beginning

# A list of devices you want to take the screenshots from
devices([
  "iPhone 18 Pro",
  "iPhone 18 Pro Max",
  "iPhone SE (3rd generation)",
])

languages([
  "en-US",
])

# The name of the scheme which contains the UI Tests
scheme("Screenshots")

# Where should the resulting screenshots be stored?
output_directory("./fastlane/screenshots")

override_status_bar(true)
disable_slide_to_type(true)
skip_open_summary(true)
concurrent_simulators(true)
clear_previous_screenshots(false)

# For more information about all available options run
# fastlane action snapshot
